name: Check Line Endings

on:
  # Trigger the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  crlf-check:
    name: Ensure there is no CRLF
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v2

      - name: Check endings (fail for CRLF, pass for LF)
        uses: erclu/check-crlf@v1
